"""YAML sidecar read/write — portable metadata mirror.

Implements the sidecar format from docs/sidecar-schema.md §1 exactly:
- schema_version 1 (integer).
- No instance-specific surrogate IDs (no DB id, no user_id).
- Flat canonical tag names.
- Creator is descriptive only (no local user_id).
- All paths relative to the item directory.
- ISO-8601 UTC timestamps.
- Regenerated header comment on every write.
- Lenient reader: unknown keys ignored, missing optional keys default to None.

YAML library: PyYAML (safe_dump / safe_load).
PyYAML is already in requirements.txt (pinned to 6.0.x via the existing venv).
We always regenerate the sidecar from structured data — no need for round-trip
comment preservation.  Recorded in docs/decisions.md.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from .paths import sidecar_path

SIDECAR_HEADER = (
    "# PartFolder 3D item sidecar — portable metadata mirror. Regenerated by the app.\n"
)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class SidecarCreator:
    name: str
    profile_url: str | None = None
    source_site: str | None = None
    is_original: bool = False


@dataclass
class SidecarFile:
    path: str
    role: str
    size: int
    sha256: str | None = None
    mtime: str | None = None  # ISO-8601 UTC string


@dataclass
class SidecarImage:
    path: str
    source: str
    order: int = 0


@dataclass
class SidecarModifiedState:
    """Records local-modification state in the sidecar (Phase 15)."""
    locally_modified: bool
    modified_at: str | None = None        # ISO-8601 UTC when divergence last detected
    source: str | None = None             # source_url at time of capture


@dataclass
class SidecarData:
    schema_version: int
    key: str
    title: str
    slug: str
    created_at: str
    updated_at: str
    description: str | None = None
    source_url: str | None = None
    source_site: str | None = None
    license: str | None = None
    creator: SidecarCreator | None = None
    tags: list[str] = field(default_factory=list)
    default_image: str | None = None
    images: list[SidecarImage] = field(default_factory=list)
    files: list[SidecarFile] = field(default_factory=list)
    # Phase 15: local-modification tracking (backward-compatible; omitted if None)
    modified_state: SidecarModifiedState | None = None


# ---------------------------------------------------------------------------
# Serialization helpers
# ---------------------------------------------------------------------------


def _dt_to_iso(dt: datetime) -> str:
    """Convert a datetime to ISO-8601 UTC string (e.g. '2026-06-27T18:40:00Z')."""
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=UTC)
    utc = dt.astimezone(UTC)
    return utc.strftime("%Y-%m-%dT%H:%M:%SZ")


def _to_dict(data: SidecarData) -> dict[str, Any]:
    """Convert a SidecarData to the ordered dict used for YAML output."""
    doc: dict[str, Any] = {
        "schema_version": data.schema_version,
        "key": data.key,
        "title": data.title,
        "slug": data.slug,
    }

    if data.description is not None:
        doc["description"] = data.description

    # source block (omit if all fields are None)
    if data.source_url or data.source_site or data.license:
        source: dict[str, Any] = {}
        if data.source_url:
            source["url"] = data.source_url
        if data.source_site:
            source["site"] = data.source_site
        if data.license:
            source["license"] = data.license
        doc["source"] = source

    if data.creator is not None:
        c = data.creator
        creator_dict: dict[str, Any] = {"name": c.name}
        if c.profile_url:
            creator_dict["profile_url"] = c.profile_url
        if c.source_site:
            creator_dict["source_site"] = c.source_site
        creator_dict["is_original"] = c.is_original
        doc["creator"] = creator_dict

    doc["tags"] = data.tags

    if data.default_image is not None:
        doc["default_image"] = data.default_image

    if data.images:
        doc["images"] = [
            {"path": img.path, "source": img.source, "order": img.order}
            for img in data.images
        ]

    if data.files:
        file_list = []
        for f in data.files:
            fd: dict[str, Any] = {"path": f.path, "role": f.role, "size": f.size}
            if f.sha256:
                fd["sha256"] = f.sha256
            if f.mtime:
                fd["mtime"] = f.mtime
            file_list.append(fd)
        doc["files"] = file_list

    doc["created_at"] = data.created_at
    doc["updated_at"] = data.updated_at

    # Phase 15: modified_state block (omit if None — backward-compatible)
    if data.modified_state is not None:
        ms = data.modified_state
        ms_dict: dict[str, Any] = {"locally_modified": ms.locally_modified}
        if ms.modified_at is not None:
            ms_dict["modified_at"] = ms.modified_at
        if ms.source is not None:
            ms_dict["source"] = ms.source
        doc["modified_state"] = ms_dict

    return doc


def _from_dict(d: dict[str, Any]) -> SidecarData:
    """Parse a YAML-loaded dict into SidecarData (lenient — ignores unknown keys)."""
    creator: SidecarCreator | None = None
    if isinstance(d.get("creator"), dict):
        cd = d["creator"]
        creator = SidecarCreator(
            name=str(cd.get("name", "")),
            profile_url=cd.get("profile_url"),
            source_site=cd.get("source_site"),
            is_original=bool(cd.get("is_original", False)),
        )

    images: list[SidecarImage] = []
    for img in d.get("images") or []:
        if isinstance(img, dict):
            images.append(SidecarImage(
                path=str(img.get("path", "")),
                source=str(img.get("source", "uploaded")),
                order=int(img.get("order", 0)),
            ))

    files: list[SidecarFile] = []
    for f in d.get("files") or []:
        if isinstance(f, dict):
            files.append(SidecarFile(
                path=str(f.get("path", "")),
                role=str(f.get("role", "other")),
                size=int(f.get("size", 0)),
                sha256=f.get("sha256"),
                mtime=f.get("mtime"),
            ))

    source = d.get("source") or {}

    # Phase 15: parse optional modified_state block (lenient)
    modified_state: SidecarModifiedState | None = None
    raw_ms = d.get("modified_state")
    if isinstance(raw_ms, dict):
        modified_state = SidecarModifiedState(
            locally_modified=bool(raw_ms.get("locally_modified", False)),
            modified_at=raw_ms.get("modified_at"),
            source=raw_ms.get("source"),
        )

    return SidecarData(
        schema_version=int(d.get("schema_version", 1)),
        key=str(d.get("key", "")),
        title=str(d.get("title", "")),
        slug=str(d.get("slug", "")),
        description=d.get("description"),
        source_url=source.get("url") if isinstance(source, dict) else None,
        source_site=source.get("site") if isinstance(source, dict) else None,
        license=source.get("license") if isinstance(source, dict) else None,
        creator=creator,
        tags=[str(t) for t in (d.get("tags") or [])],
        default_image=d.get("default_image"),
        images=images,
        files=files,
        created_at=str(d.get("created_at", "")),
        updated_at=str(d.get("updated_at", "")),
        modified_state=modified_state,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_sidecar(
    item_dir: Path,
    data: SidecarData,
    title: str,
    key: str,
) -> None:
    """Write (or overwrite) the sidecar YAML in item_dir.

    Uses write-to-temp + atomic rename to avoid partial writes.
    fsync is called on the temp file and parent directory.
    """
    dest = sidecar_path(item_dir, title, key)
    dest.parent.mkdir(parents=True, exist_ok=True)

    doc = _to_dict(data)
    content = SIDECAR_HEADER + yaml.safe_dump(
        doc,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
    )

    tmp = dest.with_suffix(".yml.tmp")
    try:
        tmp.write_text(content, encoding="utf-8")
        # fsync the temp file
        with tmp.open("rb") as fh:
            os.fsync(fh.fileno())
        tmp.replace(dest)
        # fsync the parent directory (must use os.open for directories on Linux)
        fd = os.open(str(dest.parent), os.O_RDONLY)
        try:
            os.fsync(fd)
        finally:
            os.close(fd)
    except Exception:
        tmp.unlink(missing_ok=True)
        raise


def read_sidecar(
    item_dir: Path,
    title: str,
    key: str,
) -> SidecarData | None:
    """Read the sidecar from item_dir, or return None if it does not exist.

    Lenient: unknown YAML keys are silently ignored.
    Missing optional keys default to None / empty.
    """
    src = sidecar_path(item_dir, title, key)
    if not src.exists():
        return None
    try:
        raw = yaml.safe_load(src.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        return None
    if not isinstance(raw, dict):
        return None
    return _from_dict(raw)


def build_sidecar(
    item: Any,
    tags: list[str] | None = None,
    files: list[SidecarFile] | None = None,
    images: list[SidecarImage] | None = None,
    default_image: str | None = None,
    now: datetime | None = None,
) -> SidecarData:
    """Build a SidecarData from an Item ORM object and supplementary lists.

    `item` must have: key, title, slug, description, source_url, source_site,
    license, creator (or None), created_at, updated_at.

    Phase 15: if item has locally_modified / locally_modified_at / modified_override,
    a modified_state block is written (backward-compatible; omitted when not applicable).
    """
    if now is None:
        now = datetime.now(UTC)
    updated = _dt_to_iso(now)

    creator: SidecarCreator | None = None
    if item.creator is not None:
        c = item.creator
        creator = SidecarCreator(
            name=c.name,
            profile_url=c.profile_url,
            source_site=c.source_site,
            # is_original = True only when the creator is linked to a local user
            # AND the item was explicitly flagged as self-designed (Phase 5).
            # For now: is_original = False for all imported/anonymous creators.
            is_original=False,
        )

    created_iso = (
        _dt_to_iso(item.created_at) if item.created_at else _dt_to_iso(now)
    )
    updated_iso = (
        _dt_to_iso(item.updated_at) if item.updated_at else updated
    )

    # Phase 15: build modified_state block when modification tracking data is present.
    # Only write when the item has a source_url (the feature is opt-in by source).
    modified_state: SidecarModifiedState | None = None
    source_url_val = getattr(item, "source_url", None)
    locally_modified_val = getattr(item, "locally_modified", False)
    locally_modified_at_val = getattr(item, "locally_modified_at", None)
    modified_override_val = getattr(item, "modified_override", None)
    if source_url_val:
        # Effective state
        effective = (
            modified_override_val == "modified"
            if modified_override_val is not None
            else bool(locally_modified_val)
        )
        modified_at_iso: str | None = None
        if locally_modified_at_val is not None:
            modified_at_iso = _dt_to_iso(locally_modified_at_val)
        modified_state = SidecarModifiedState(
            locally_modified=effective,
            modified_at=modified_at_iso,
            source=source_url_val,
        )

    return SidecarData(
        schema_version=item.schema_version,
        key=item.key,
        title=item.title,
        slug=item.slug,
        description=item.description,
        source_url=item.source_url,
        source_site=item.source_site,
        license=item.license,
        creator=creator,
        tags=tags or [],
        default_image=default_image,
        images=images or [],
        files=files or [],
        created_at=created_iso,
        updated_at=updated_iso,
        modified_state=modified_state,
    )
