"""Phase 7 tests: print history, gcode parser, print stats, and security.

Tests are split into:
1. Pure unit tests for the gcode parser (no DB needed)
2. DB-backed API tests for print record CRUD
3. Security tests proving private records never leak
4. Print stats tests
"""

from __future__ import annotations

import pytest
from httpx import AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession

from app.storage.gcode_parser import _parse_time_str, parse_gcode_text

# ---------------------------------------------------------------------------
# 1. gcode parser — pure unit tests (no DB, no fixtures needed)
# ---------------------------------------------------------------------------


class TestGcodeTimeParser:
    """Test _parse_time_str with various time formats."""

    def test_hours_minutes_seconds(self) -> None:
        assert _parse_time_str("2h 3m 45s") == 7425

    def test_hours_minutes_only(self) -> None:
        assert _parse_time_str("1h 2m") == 3720

    def test_minutes_seconds_only(self) -> None:
        assert _parse_time_str("5m 30s") == 330

    def test_hours_only(self) -> None:
        assert _parse_time_str("3h") == 10800

    def test_seconds_only(self) -> None:
        assert _parse_time_str("90s") == 90

    def test_days(self) -> None:
        # 1d=86400 + 2h=7200 + 30m=1800 = 95400
        assert _parse_time_str("1d 2h 30m") == 95400

    def test_zero(self) -> None:
        assert _parse_time_str("0h 0m 0s") == 0

    def test_garbage(self) -> None:
        assert _parse_time_str("not a time") is None

    def test_empty(self) -> None:
        assert _parse_time_str("") is None


class TestGcodeParserPrusa:
    """Test Prusa Slicer dialect parsing."""

    PRUSA_HEADER = """\
; generated by PrusaSlicer 2.7.4+win64
; external_perimeters_first = 0
; filament used [mm] = 1234.56
; filament used [cm3] = 2.34
; filament used [g] = 6.78
; filament cost [money] = 0.20
; total filament used [g] = 6.78
; estimated printing time (normal mode) = 2h 3m 45s
; estimated printing time (silent mode) = 3h 10m
G28
"""

    def test_prusa_filament_mm(self) -> None:
        m = parse_gcode_text(self.PRUSA_HEADER)
        assert m.filament_length_mm == pytest.approx(1234.56)

    def test_prusa_filament_g(self) -> None:
        m = parse_gcode_text(self.PRUSA_HEADER)
        assert m.filament_weight_g == pytest.approx(6.78)

    def test_prusa_print_time(self) -> None:
        m = parse_gcode_text(self.PRUSA_HEADER)
        assert m.estimated_print_time_s == 7425  # 2*3600 + 3*60 + 45

    def test_prusa_slicer_detected(self) -> None:
        m = parse_gcode_text(self.PRUSA_HEADER)
        assert m.slicer == "prusa"

    def test_no_errors(self) -> None:
        m = parse_gcode_text(self.PRUSA_HEADER)
        assert m.parse_errors == []


class TestGcodeParserOrcaSlicer:
    """Test Orca Slicer dialect parsing."""

    ORCA_HEADER = """\
; generated by OrcaSlicer 2.1.1
; filament used [mm] = 2500.0
; filament used [g] = 7.50
; total estimated time = 1h 15m 30s
G28
"""

    def test_orca_filament_mm(self) -> None:
        m = parse_gcode_text(self.ORCA_HEADER)
        assert m.filament_length_mm == pytest.approx(2500.0)

    def test_orca_filament_g(self) -> None:
        m = parse_gcode_text(self.ORCA_HEADER)
        assert m.filament_weight_g == pytest.approx(7.50)

    def test_orca_print_time(self) -> None:
        m = parse_gcode_text(self.ORCA_HEADER)
        # 1*3600 + 15*60 + 30 = 4530
        assert m.estimated_print_time_s == 4530

    def test_orca_slicer_detected(self) -> None:
        m = parse_gcode_text(self.ORCA_HEADER)
        assert m.slicer == "orca"


class TestGcodeParserCura:
    """Test Cura dialect parsing."""

    CURA_HEADER = """\
;FLAVOR:Marlin
;Generated with Cura_SteamEngine 5.8.0
;TIME:7890
;Filament used: 1.23m
;Layer height: 0.2
;MINX:10
M109 S210
"""

    def test_cura_filament_mm(self) -> None:
        m = parse_gcode_text(self.CURA_HEADER)
        # 1.23 m → 1230 mm
        assert m.filament_length_mm == pytest.approx(1230.0)

    def test_cura_print_time(self) -> None:
        m = parse_gcode_text(self.CURA_HEADER)
        assert m.estimated_print_time_s == 7890

    def test_cura_slicer_detected(self) -> None:
        m = parse_gcode_text(self.CURA_HEADER)
        assert m.slicer == "cura"

    def test_cura_no_weight(self) -> None:
        # Cura doesn't provide weight directly
        m = parse_gcode_text(self.CURA_HEADER)
        assert m.filament_weight_g is None


class TestGcodeParserBambu:
    """Test Bambu Studio dialect parsing."""

    BAMBU_HEADER = """\
; HEADER_BLOCK_START
; generated by Bambu Studio 01.09.05.52
; total filament used [g] = 8.23
; total estimated time = 45m 20s
; filament used [mm] = 3456.7
;totalTime:2720
; HEADER_BLOCK_END
G28
"""

    def test_bambu_filament_mm(self) -> None:
        m = parse_gcode_text(self.BAMBU_HEADER)
        assert m.filament_length_mm == pytest.approx(3456.7)

    def test_bambu_filament_g(self) -> None:
        m = parse_gcode_text(self.BAMBU_HEADER)
        assert m.filament_weight_g == pytest.approx(8.23)

    def test_bambu_print_time_from_comment(self) -> None:
        m = parse_gcode_text(self.BAMBU_HEADER)
        # 45*60 + 20 = 2720 — but the "total estimated time" line should win over ;totalTime:
        # The comment pattern is tried first.
        assert m.estimated_print_time_s == 2720

    def test_bambu_slicer_detected(self) -> None:
        m = parse_gcode_text(self.BAMBU_HEADER)
        assert m.slicer == "bambu"


class TestGcodeParserBambuTotalTimeOnly:
    """Test Bambu ;totalTime:X fallback."""

    BAMBU_SHORT = """\
; generated by Bambu Studio 01.09
; total filament used [g] = 5.0
;totalTime:3600
G28
"""

    def test_bambu_total_time_fallback(self) -> None:
        m = parse_gcode_text(self.BAMBU_SHORT)
        assert m.estimated_print_time_s == 3600


class TestGcodeParserEmpty:
    """Test empty / whitespace inputs."""

    def test_empty_string(self) -> None:
        m = parse_gcode_text("")
        assert m.filament_length_mm is None
        assert m.filament_weight_g is None
        assert m.estimated_print_time_s is None
        assert m.slicer is None
        assert m.parse_errors == []

    def test_no_comment_lines(self) -> None:
        m = parse_gcode_text("G28\nG1 X0 Y0\n")
        assert m.filament_length_mm is None


class TestGcodeParserFile:
    """Test parse_gcode_file for binary / unknown extensions."""

    def test_bgcode_returns_empty(self, tmp_path: object) -> None:
        from pathlib import Path  # noqa: PLC0415

        from app.storage.gcode_parser import parse_gcode_file  # noqa: PLC0415

        p = Path(str(tmp_path)) / "job.bgcode"  # type: ignore[arg-type]
        p.write_bytes(b"\x00\x01\x02\x03")
        m = parse_gcode_file(p)
        assert m.filament_length_mm is None
        assert m.parse_errors == []

    def test_gcode_file_parsed(self, tmp_path: object) -> None:
        from pathlib import Path  # noqa: PLC0415

        from app.storage.gcode_parser import parse_gcode_file  # noqa: PLC0415

        content = "; filament used [mm] = 500.0\n;TIME:120\n"
        p = Path(str(tmp_path)) / "job.gcode"  # type: ignore[arg-type]
        p.write_text(content, encoding="utf-8")
        m = parse_gcode_file(p)
        assert m.filament_length_mm == pytest.approx(500.0)
        assert m.estimated_print_time_s == 120

    def test_missing_file_returns_error(self, tmp_path: object) -> None:
        from pathlib import Path  # noqa: PLC0415

        from app.storage.gcode_parser import parse_gcode_file  # noqa: PLC0415

        p = Path(str(tmp_path)) / "nonexistent.gcode"  # type: ignore[arg-type]
        m = parse_gcode_file(p)
        assert m.parse_errors != []


# ---------------------------------------------------------------------------
# Helpers for DB-backed tests
# ---------------------------------------------------------------------------


async def _setup_admin(client: AsyncClient) -> str:
    """Setup instance and return CSRF token."""
    await client.post(
        "/api/setup",
        json={
            "admin_email": "admin@test.com",
            "admin_name": "Admin",
            "admin_password": "password1234",
        },
    )
    resp = await client.post(
        "/api/auth/login",
        json={"email": "admin@test.com", "password": "password1234"},
    )
    assert resp.status_code == 200
    return client.cookies.get("pf3d_csrf", "")


async def _create_item(
    client: AsyncClient, csrf: str, db: AsyncSession
) -> tuple[int, str]:
    """Create a library + item, return (item_id, item_key)."""
    import tempfile

    tmpdir = tempfile.mkdtemp()

    lib_resp = await client.post(
        "/api/libraries",
        json={"name": "Test Library", "mount_path": tmpdir},
        headers={"X-CSRF-Token": csrf},
    )
    assert lib_resp.status_code == 201, lib_resp.text
    lib_id = lib_resp.json()["id"]

    item_resp = await client.post(
        "/api/items",
        json={"title": "Test Widget", "library_id": lib_id},
        headers={"X-CSRF-Token": csrf},
    )
    assert item_resp.status_code == 201, item_resp.text
    data = item_resp.json()
    return data["id"], data["key"]


# ---------------------------------------------------------------------------
# 2. Print record CRUD
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_create_print_record(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    resp = await client.post(
        f"/api/items/{key}/print-records",
        json={"note": "Great print!", "visibility": "public", "success": True},
        headers={"X-CSRF-Token": csrf},
    )
    assert resp.status_code == 201, resp.text
    data = resp.json()
    assert data["note"] == "Great print!"
    assert data["visibility"] == "public"
    assert data["success"] is True
    assert data["item_key"] == key


@pytest.mark.asyncio
async def test_create_print_record_private_default(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    resp = await client.post(
        f"/api/items/{key}/print-records",
        json={"note": "Secret notes"},
        headers={"X-CSRF-Token": csrf},
    )
    assert resp.status_code == 201
    assert resp.json()["visibility"] == "private"


@pytest.mark.asyncio
async def test_list_print_records(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    # Create two records
    for note, vis in [("Public note", "public"), ("Private note", "private")]:
        r = await client.post(
            f"/api/items/{key}/print-records",
            json={"note": note, "visibility": vis},
            headers={"X-CSRF-Token": csrf},
        )
        assert r.status_code == 201

    resp = await client.get(f"/api/items/{key}/print-records")
    assert resp.status_code == 200
    records = resp.json()
    assert len(records) == 2


@pytest.mark.asyncio
async def test_update_print_record(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    create_resp = await client.post(
        f"/api/items/{key}/print-records",
        json={"note": "Original"},
        headers={"X-CSRF-Token": csrf},
    )
    rec_id = create_resp.json()["id"]

    patch_resp = await client.patch(
        f"/api/items/{key}/print-records/{rec_id}",
        json={"note": "Updated", "success": False, "rating": 2},
        headers={"X-CSRF-Token": csrf},
    )
    assert patch_resp.status_code == 200
    data = patch_resp.json()
    assert data["note"] == "Updated"
    assert data["success"] is False
    assert data["rating"] == 2


@pytest.mark.asyncio
async def test_delete_print_record(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    create_resp = await client.post(
        f"/api/items/{key}/print-records",
        json={"note": "To delete"},
        headers={"X-CSRF-Token": csrf},
    )
    rec_id = create_resp.json()["id"]

    del_resp = await client.delete(
        f"/api/items/{key}/print-records/{rec_id}",
        headers={"X-CSRF-Token": csrf},
    )
    assert del_resp.status_code == 204

    list_resp = await client.get(f"/api/items/{key}/print-records")
    assert list_resp.status_code == 200
    assert list_resp.json() == []


# ---------------------------------------------------------------------------
# 3. Print stats
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_print_stats_empty(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    await _setup_admin(client)

    resp = await client.get("/api/print-stats")
    assert resp.status_code == 200
    data = resp.json()
    assert data["total_prints"] == 0
    assert data["success_count"] == 0
    assert data["fail_count"] == 0
    assert data["success_rate"] is None
    assert data["total_filament_length_mm"] == 0.0
    assert data["total_print_time_s"] == 0


@pytest.mark.asyncio
async def test_print_stats_with_data(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    # Create 3 print records: 2 success, 1 fail
    records = [
        {"success": True, "note": "ok"},
        {"success": True, "note": "ok2"},
        {"success": False, "note": "failed"},
    ]
    for r in records:
        await client.post(
            f"/api/items/{key}/print-records",
            json=r,
            headers={"X-CSRF-Token": csrf},
        )

    resp = await client.get("/api/print-stats")
    assert resp.status_code == 200
    data = resp.json()
    assert data["total_prints"] == 3
    assert data["success_count"] == 2
    assert data["fail_count"] == 1
    assert data["success_rate"] == pytest.approx(2 / 3)
    assert len(data["most_printed_items"]) >= 1
    assert data["most_printed_items"][0]["count"] == 3


# ---------------------------------------------------------------------------
# 4. SECURITY: private records never leak
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_unauthenticated_cannot_list_print_records(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    """An unauthenticated request to the print-records list returns 401."""
    csrf = await _setup_admin(client)
    _, key = await _create_item(client, csrf, db_session)

    await client.post(
        f"/api/items/{key}/print-records",
        json={"note": "Private note", "visibility": "private"},
        headers={"X-CSRF-Token": csrf},
    )

    # Log out
    await client.post("/api/auth/logout", headers={"X-CSRF-Token": csrf})

    # Try to list — should get 401
    resp = await client.get(f"/api/items/{key}/print-records")
    assert resp.status_code in (401, 403), (
        f"Expected 401/403 but got {resp.status_code}: {resp.text}"
    )


@pytest.mark.asyncio
async def test_print_stats_unauthenticated_denied(
    client: AsyncClient, db_session: AsyncSession
) -> None:
    """Print stats endpoint requires authentication without prior login."""
    # No setup / login — hitting the endpoint cold
    resp = await client.get("/api/print-stats")
    assert resp.status_code in (401, 403)
