#!/bin/sh
# PartFolder 3D — optional TLS/HTTPS assembly.
#
# Runs once per container start via the stock nginx image's
# /docker-entrypoint.d/ mechanism, BEFORE nginx itself starts. POSIX sh
# (alpine has no bash). Idempotent — safe to re-run on every restart. Never
# logs certificate/key material.
#
# TLS_MODE (see .env.example / docs/tls.md):
#   off        (default) plain :80 only — today's behavior, unchanged.
#   selfsigned generate (if absent) a self-signed cert into $CERT_DIR and
#              serve :443 with it. Browsers show a trust warning — expected.
#   provided   $CERT_DIR/fullchain.pem + privkey.pem must already be mounted
#              (a real, bring-your-own cert). Missing/empty files fail
#              LOUDLY (non-zero exit) — this container NEVER silently falls
#              back to plain HTTP when TLS was requested.
#
# TLS_REDIRECT=true (only meaningful when TLS_MODE != off): the baked :80
# server 301-redirects every request to https://$host$request_uri.

set -e

TLS_MODE="${TLS_MODE:-off}"
TLS_REDIRECT="${TLS_REDIRECT:-false}"
CERT_DIR="${CERT_DIR:-/etc/nginx/certs}"
TLS_CONF_FILE="/etc/nginx/conf.d/tls.conf"
REDIRECT_CONF_FILE="/etc/nginx/partfolder-redirect.conf"

reset_redirect() {
    cat > "$REDIRECT_CONF_FILE" <<'EOF'
# Runtime-generated by nginx/40-partfolder-tls.sh — do not edit by hand.
# Empty: plain HTTP passthrough (TLS_MODE=off or TLS_REDIRECT=false).
EOF
}

case "$TLS_MODE" in
    off)
        # Ensure no stray tls.conf/redirect survives a mode switch (e.g. a
        # cert volume that previously ran selfsigned/provided, now back to off).
        rm -f "$TLS_CONF_FILE"
        reset_redirect
        echo "[partfolder-tls] TLS_MODE=off — plain :80 only (unchanged behavior)."
        exit 0
        ;;
    selfsigned)
        mkdir -p "$CERT_DIR"
        if [ ! -s "$CERT_DIR/privkey.pem" ] || [ ! -s "$CERT_DIR/fullchain.pem" ]; then
            echo "[partfolder-tls] TLS_MODE=selfsigned: no cert found in $CERT_DIR, generating one (CN=${TLS_CN:-localhost})..."
            openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
                -keyout "$CERT_DIR/privkey.pem" \
                -out "$CERT_DIR/fullchain.pem" \
                -subj "/CN=${TLS_CN:-localhost}" >/dev/null 2>&1
            chmod 600 "$CERT_DIR/privkey.pem"
            echo "[partfolder-tls] self-signed cert generated — browsers will show a trust warning."
        else
            echo "[partfolder-tls] TLS_MODE=selfsigned: reusing existing cert in $CERT_DIR (not regenerating)."
        fi
        ;;
    provided)
        if [ ! -s "$CERT_DIR/fullchain.pem" ] || [ ! -s "$CERT_DIR/privkey.pem" ]; then
            echo "[partfolder-tls] FATAL: TLS_MODE=provided but $CERT_DIR/fullchain.pem and/or" >&2
            echo "[partfolder-tls]        $CERT_DIR/privkey.pem is missing or empty." >&2
            echo "[partfolder-tls] Mount your real certificate files into $CERT_DIR (see" >&2
            echo "[partfolder-tls] .env.example / docs/tls.md) and retry." >&2
            echo "[partfolder-tls] Refusing to start — silently falling back to plain HTTP" >&2
            echo "[partfolder-tls] would be worse than failing loudly." >&2
            exit 1
        fi
        echo "[partfolder-tls] TLS_MODE=provided: using mounted cert in $CERT_DIR."
        ;;
    *)
        echo "[partfolder-tls] FATAL: unknown TLS_MODE='$TLS_MODE' (expected off|selfsigned|provided)." >&2
        exit 1
        ;;
esac

# selfsigned or provided reach here with a valid cert pair in $CERT_DIR.
cat > "$TLS_CONF_FILE" <<EOF
server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     $CERT_DIR/fullchain.pem;
    ssl_certificate_key $CERT_DIR/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5:!3DES;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    include /etc/nginx/partfolder-common.conf;
}
EOF
echo "[partfolder-tls] wrote $TLS_CONF_FILE (TLS_MODE=$TLS_MODE)."

if [ "$TLS_REDIRECT" = "true" ]; then
    cat > "$REDIRECT_CONF_FILE" <<'EOF'
# Runtime-generated by nginx/40-partfolder-tls.sh — do not edit by hand.
# TLS_REDIRECT=true: redirect all plain-HTTP requests to HTTPS.
return 301 https://$host$request_uri;
EOF
    echo "[partfolder-tls] TLS_REDIRECT=true: :80 will 301-redirect to https://\$host\$request_uri."
else
    reset_redirect
fi
